apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: sealedsecret
spec:
  encryptedData:
    foo: AgA/X+uWcPfT2jzDTKB34INBb37bvMqlwsDBGehzT9NsaBu16GQk3PJJEHz3BTOtXzeQiVF3LxGkX3PCjoz+7EBQnlCIWZh08FE3CkuG1tNR7vjn1Fb9wrwoy7S4xRoy3Iq5WuhwvH8KaOk6smdtr1qKjIRi9Mu7IQgabfTrXnJ28nY+yyLWGT76I8umTUUSS9tY/Ko23Pf+rlGabnuaWJD4LFd5OQM2nqe63qz02l/m+qCfIMZc9np0goSuBWwCCujH8XcruPTKwS/hndRF8/sNzQNBEHfzA/100vXHzXKF+rkmxzeOKI9K4s7jAxGMQqYAW/o6SeFw/khse0YlGEbbmaXJ2EV05/pn46Le9ZVl0am300L7yl3yrPWkbgKqWpHB4xt2ZvUJ6pMeF7HEu8/B8tTLLRqfLJgE9aWvlfDI3qvpc0+yu1Q0Fe9z+fYIiHIvcYXcA58cXrloEaCQE664iSR92Ja14XmfQpUwG4nfCDP26x3s33vr42kKcv0pg/CyE3THTus/hgzv5RQOG/65DO7OmvMS+yPxXz6r/kjeQGbHBXEMXUjKo9LsoYqDwgUgq3kGx2IZ+3MvZ6l9riN1vaYAEcO2+hhnpdLMwNSkZA2aturGfc+XwqdakUBkGtj8pzuZxYc3cfgBD8/b1mO46BP8zjPLpkD7qE3LBDZPSVxYeTYQNotJyhZqyG7BfrYA/Ds=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
